// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-tX0ghWiag19xSBM82_oLNALTpCpNtY',
    appId: '1:707796651782:web:15e371c2b84c43437b1887',
    messagingSenderId: '707796651782',
    projectId: 'foodcourier-71da7',
    authDomain: 'foodcourier-71da7.firebaseapp.com',
    storageBucket: 'foodcourier-71da7.firebasestorage.app',
    measurementId: 'G-ZDZCE05V2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe1QM1kD4mRtfj67ZQ4iBZtecHKCwmbLY',
    appId: '1:707796651782:android:fa59b79b2af269517b1887',
    messagingSenderId: '707796651782',
    projectId: 'foodcourier-71da7',
    storageBucket: 'foodcourier-71da7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD-XHaUFhlt4zSKRKXN2c9ND4o5jPJzh8',
    appId: '1:707796651782:ios:af5907992800770d7b1887',
    messagingSenderId: '707796651782',
    projectId: 'foodcourier-71da7',
    storageBucket: 'foodcourier-71da7.firebasestorage.app',
    iosBundleId: 'com.example.foodcourier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx-tX0ghWiag19xSBM82_oLNALTpCpNtY',
    appId: '1:707796651782:web:a336d0ed3ec5ab467b1887',
    messagingSenderId: '707796651782',
    projectId: 'foodcourier-71da7',
    authDomain: 'foodcourier-71da7.firebaseapp.com',
    storageBucket: 'foodcourier-71da7.firebasestorage.app',
    measurementId: 'G-HN1M09E005',
  );
}
